#pragma once

#include <map>
#include <cassert>
#include <vector>
#include <random>
#include <filesystem>
#include <stack>
#include <set>
#include <bitset>
#include "nlohmann_json.h"
#include "bitset2/bitset2.hpp"
#include "core/fanDebug.hpp"
#include "core/fanColor.hpp"
#include "core/math/fanVector2.hpp"
#include "core/math/fanMathUtils.hpp"
#include "core/fanSignal.hpp"
#include "core/imgui/fanModals.hpp"
#include "render/fanRenderGlobal.hpp"